//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DIEULINH\\LINH;Initial Catalog=LTMT1_K14_BUITHIDIEULINH_CD220337_QuanL" +
            "yDiemCNTT;Integrated Security=True;Encrypt=True;TrustServerCertificate=True")]
        public string LTMT1_K14_BUITHIDIEULINH_CD220337_QuanLyDiemCNTTConnectionString {
            get {
                return ((string)(this["LTMT1_K14_BUITHIDIEULINH_CD220337_QuanLyDiemCNTTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-25KM0HC\\MSSQLSERVER02;Initial Catalog=Diem_DATN;Integrated Se" +
            "curity=True;TrustServerCertificate=True")]
        public string Diem_DATNConnectionString {
            get {
                return ((string)(this["Diem_DATNConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-25KM0HC\\MSSQLSERVER02;Initial Catalog=DATN;Integrated Securit" +
            "y=True;TrustServerCertificate=True")]
        public string DATNConnectionString {
            get {
                return ((string)(this["DATNConnectionString"]));
            }
        }
    }
}
